### ISSUE TITLE
禁止首页(root view)滑动 

### ISSUE THREAD

**Issue by naivehhr** [slashhuang/react-native-demo#1]
Hello，RN中遇到个问题，请教下：
问题：当navigator回退到首页的时候页面还可以滑动，怎么设置当到根页面的时候就不滑动呢？
首页Navigator设置如下：

```
render() {
      var defaultName = 'AppComponent';
      var defaultComponent = App;
      return (
        <Navigator
          initialRoute={{ name: defaultName,component: defaultComponent }}
          configureScene={(route) => {
            return route.sceneConfig || Navigator.SceneConfigs.HorizontalSwipeJump;
          }}
          renderScene={(route, navigator) => {
            let Component  = route.component;
            _navigator = navigator 
            return <Component {...route.params} navigator={navigator} />
          }}/>
      );
    }
```

![ers](https://cloud.githubusercontent.com/assets/5243456/14169796/71f8fc1c-f75c-11e5-97e3-2bcab0d99bb4.gif)

**Comment by slashhuang** [comment]
你看下Navigator.SceneConfigs.HorizontalSwipeJump,  它里面有个gestures属性，如果置为null，即可去除滑动,如果仅仅将gestures.jumpForward置为null，则不允许向前切换界面

**Comment by slashhuang** [comment]
@naivehhr `configureScene={(route) => {
            let  gestureType = Navigator.SceneConfigs.HorizontalSwipeJump;
            gestureType.gestures=null;
             return gestureType
          }}`

**Comment by naivehhr** [comment]
搞定，多谢！！
