### ISSUE TITLE
运行后报错找不到Slider.js

### ISSUE THREAD

**Issue by wuhuixuan** [slashhuang/react-native-demo#2]
你好！demo很棒
不过运行后报错说找不到Slider.js，这个文件的位置没放对

**Comment by slashhuang** [comment]
好的，我马上看下 @wuhuixuan

**Comment by slashhuang** [comment]
这个问题应该你自己能够解决。由于最新的react-native版本也在不断提升，所以在这个demo上面可能安装npm包的时候会有细节上的bug。欢迎提pull request

**Comment by ningkaikok** [comment]
修改Slider.js 名字为Swiper.js 可以跑。不明觉厉

**Comment by slashhuang** [comment]
@ningkaikok  thank u。好久没更新这个repo了，准备过段时间新增react-native的API，欢迎提PR~
